#!/bin/bash
# Docker Boots:
docker run --detach --publish 4150:4150 --publish 4151:4151 --name nsqd     nsqio/nsqd
docker run --detach --publish 4171:4171                     --name nsqadmin nsqio/nsqadmin -nsqd-http-address=192.168.1.4:4151
docker run --detach --publish 27017:27017                   --name o8-mongo mongo
docker run --detach --publish 4001:4001 --publish 7001:7001 --name etcd     microbox/etcd:latest -name config -cors '*' -cluster-active-size 1
