#!/bin/bash
IP=$(ip addr | awk '/inet 192/ { sub(/\/[0-9]+/, "", $2); print $2 }')
# Docker Boots:
docker run --detach --name etcd --publish 4001:4001 --publish 7001:7001 microbox/etcd:latest -name config -cors '*' -cluster-active-size 1
# docker run --detach --name o8-mongo --publish 27017:27017 --volume /data/database/o8-mongo:/data mongo
docker run --detach --name nsqlookupd --publish 4160:4160 --publish 4161:4161 nsqio/nsqlookupd
docker run --detach --name nsqd --publish 4150:4150 --publish 4151:4151 nsqio/nsqd --broadcast-address=${IP} --lookupd-tcp-address=172.17.42.1:4160
docker run --detach --name nsqadmin --publish 4171:4171 nsqio/nsqadmin -lookupd-http-address=172.17.42.1:4161
cat <<CONFIG > /data/database/o8-elastic/elasticsearch.yml
path:
  logs: /data/log
  data: /data/data
CONFIG
docker run --detach --name o8-elastic --publish 9200:9200 --publish 9300:9300 --volume /data/database/o8-elastic:/data dockerfile/elasticsearch /elasticsearch/bin/elasticsearch -Des.config=/data/elasticsearch.yml
docker run --detach --name o8-mariadb --publish 3307:3306 dockerfile/mariadb:latest
